version: '2'

services:
  dev-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./requirements.txt:/app/requirements.txt
      - ./requirements-dev.txt:/app/requirements-dev.txt
      - pip-cache:/root/.cache
    ports:
      - "8000:8000"
      - "8001:8001"
    stdin_open: true
    command: bash -c "pip install -r requirements.txt &&
             pip install -r requirements-dev.txt &&
             gunicorn src.runner:app --bind 0.0.0.0:8080 --worker-class aiohttp.worker.GunicornWebWorker -w 1 --reload"

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./requirements.txt:/app/requirements.txt
      - ./requirements-dev.txt:/app/requirements-dev.txt
      - pip-cache:/root/.cache
    stdin_open: true
    command: bash -c "pip install -r requirements.txt &&
             pip install -r requirements-dev.txt &&
             ptw src -- -s"


volumes:
  pip-cache:
    driver: local
