branch-defaults:
  master:
    environment: py-fb-bot-dev
    group_suffix: null
global:
  application_name: py-fb-bot
  default_ec2_keyname: py-fb-bot
  default_platform: Multi-container Docker 1.11.2 (Generic)
  default_region: eu-central-1
  profile: null
  sc: git
